// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// estratofun
List estratofun(CharacterVector estrato);
RcppExport SEXP StQTFun_estratofun(SEXP estratoSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< CharacterVector >::type estrato(estratoSEXP);
    __result = Rcpp::wrap(estratofun(estrato));
    return __result;
END_RCPP
}
