# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

estratofun <- function(estrato) {
    .Call('StQTFun_estratofun', PACKAGE = 'StQTFun', estrato)
}

nn3aux <- function(cinv, idreceivers, strreceivers, matreceivers, iddonors, strdonors, matdonors) {
    .Call('StQTFun_nn3aux', PACKAGE = 'StQTFun', cinv, idreceivers, strreceivers, matreceivers, iddonors, strdonors, matdonors)
}

CountGroup <- function(v) {
    .Call('StQTFun_CountGroup', PACKAGE = 'StQTFun', v)
}

